// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"oil/config"
	"oil/infras/jwt"
	"oil/infras/otel"
	"oil/infras/postgres"
	"oil/infras/redis"
	"oil/infras/s3"
	"oil/internal/domains/auth/service"
	repository3 "oil/internal/domains/booking/repository"
	service3 "oil/internal/domains/booking/service"
	repository2 "oil/internal/domains/room/repository"
	service2 "oil/internal/domains/room/service"
	"oil/internal/domains/user/repository"
	"oil/internal/handlers/auth"
	"oil/internal/handlers/booking"
	"oil/internal/handlers/room"
	"oil/permissions"
	"oil/shared/cache"
	"oil/transport/http"
	"oil/transport/http/middleware"
	"oil/transport/http/router"
)

// Injectors from wire.go:

func InitializeService() *http.HTTP {
	configConfig := config.Get()
	connection := postgres.New(configConfig)
	otelOtel := otel.New(configConfig)
	user := repository.New(connection, otelOtel)
	client := redis.New(configConfig)
	redisCache := cache.NewRedisCache(client, otelOtel)
	jwtJWT := jwt.New(configConfig, redisCache)
	serviceAuth := service.New(user, configConfig, otelOtel, jwtJWT)
	handler := auth.New(serviceAuth, otelOtel)
	repositoryRoom := repository2.New(connection, otelOtel)
	s3S3 := s3.New(configConfig, otelOtel)
	serviceRoom := service2.New(repositoryRoom, configConfig, redisCache, otelOtel, s3S3)
	roomHandler := room.New(serviceRoom, otelOtel)
	repositoryBooking := repository3.New(connection, otelOtel)
	serviceBooking := service3.New(repositoryBooking, repositoryRoom, configConfig, redisCache, otelOtel)
	bookingHandler := booking.New(serviceBooking, otelOtel)
	domainHandlers := router.DomainHandlers{
		Auth:    handler,
		Room:    roomHandler,
		Booking: bookingHandler,
	}
	routerRouter := router.New(domainHandlers)
	appMiddleware := middleware.NewAppMiddleware(otelOtel, configConfig, redisCache)
	permissionData := permissions.Get()
	authRole := middleware.NewAuthRoleMiddleware(jwtJWT, otelOtel, permissionData, configConfig)
	httpHTTP := http.New(configConfig, routerRouter, connection, appMiddleware, authRole)
	return httpHTTP
}

// wire.go:

var configurations = wire.NewSet(config.Get, permissions.Get)

var infrastructures = wire.NewSet(postgres.New, otel.New, redis.New, s3.New, jwt.New)

var middlewares = wire.NewSet(middleware.NewAppMiddleware, middleware.NewAuthRoleMiddleware)

var sharedHelpers = wire.NewSet(cache.NewRedisCache)

var roomDomain = wire.NewSet(repository2.New, service2.New)

var bookingDomain = wire.NewSet(repository3.New, service3.New)

var authDomain = wire.NewSet(repository.New, service.New)

var domains = wire.NewSet(
	authDomain,
	roomDomain,
	bookingDomain,
)

var routing = wire.NewSet(wire.Struct(new(router.DomainHandlers), "*"), auth.New, room.New, booking.New, router.New)
